---
- name: Add ppa Repository
  become: true
  apt_repository: "repo=ppa:ondrej/{{ php.ppa }}"

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install php v{{ php_version }}
  become: true
  apt: pkg=php{{ php_version }} state=latest

- name: Install php{{ php_version }}-fpm
  become: true
  apt: pkg=php{{ php_version }}-fpm state=latest

- name: Install PHP Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: "{{ php.packages | default([]) }}"

- include: configure.yml
- include: pecl.yml
